### ISSUE TITLE
RATS

### ISSUE THREAD

**Issue by gold1lock5** [Minecraft-Eternal/MC-Eternal-Lite-1.12#1]
The RATS mod has not been updated to reflect the new changes, specifically I can not craft the "Angel" upgrade to create a rat that will respawn. I play with friends and RATS is kinda the only thing that keeps me going... Hopefully this can be resolved so I can craft this item. Thank you!

**Comment by anabsolutesloth** [comment]
The Angel upgrade for Rats is part of versions of Rats for newer Minecraft versions, i can't do anything about this.
