### ISSUE TITLE
no quests

### ISSUE THREAD

**Issue by adamlolgaming** [Minecraft-Eternal/MC-Eternal-Lite-1.12#10]
### Description of the Bug

when downloading and launching on crystal launcher there are no quests or things to buy

### Expected Behaviour

there  should be quests and things in shop

### Modpack Version

1.3.8.1

### Screenshots

![obraz](https://user-images.githubusercontent.com/94706391/142669383-641463f8-9460-4200-96ba-cacf8d8206b4.png)
![obraz](https://user-images.githubusercontent.com/94706391/142669474-a7798f34-3d51-4735-8dad-e868283129d6.png)

**Comment by anabsolutesloth** [comment]
Bad Install, reinstall.
