### ISSUE TITLE
When my friend and I were playing together, I was the host and he had a serious freeze.

### ISSUE THREAD

**Issue by konsheng** [Minecraft-Eternal/MC-Eternal-Lite-1.12#11]
### Description of the Bug

When my friend and I were playing together, I was the host and he had a serious freeze.

### Expected Behaviour

Solve this serious problem

### Modpack Version

MC Eternal Lite 1.3.8.1

### Screenshots

No

### Log

in Extra Info

### Extra Info

[debug.txt](https://github.com/Minecraft-Eternal/MC-Eternal-Lite-1.12/files/7655664/debug.txt)
[logs.txt](https://github.com/Minecraft-Eternal/MC-Eternal-Lite-1.12/files/7655665/logs.txt)

**Comment by anabsolutesloth** [comment]
I don't think there's much i can do about this, if i find something, i'll reopen this.
