### ISSUE TITLE
Increase Chest Transporter Mod

### ISSUE THREAD

**Issue by konsheng** [Minecraft-Eternal/MC-Eternal-Lite-1.12#12]
### Description of Suggestion

Increase Chest Transporter Mod
https://www.curseforge.com/minecraft/mc-mods/chest-transporter😘

### How does this improve the experience?

Can move the box more conveniently。

### Screenshots

no

**Comment by anabsolutesloth** [comment]
Use Cardboard Boxes.
I won't be adding really any mods unless they are in full MCE or help performance.
