### ISSUE TITLE
All the mobs are named Primordium 5th Legion

### ISSUE THREAD

**Issue by elexe07** [Minecraft-Eternal/MC-Eternal-Lite-1.12#14]
### Description of the Bug

All the mobs, either pacific or hostile spawns with a lot of hp and are named Primordium the 5th, i cant play like this, how can i solve this?

### Expected Behaviour

All the mobs, either pacific or hostile spawns with a lot of hp and are named Primordium the 5th, i cant play like this, how can i solve this?

### Modpack Version

1.3.8.1

**Comment by anabsolutesloth** [comment]
Do you have Optifine?

**Comment by z3ttee** [comment]
We have the same issue currently. We removed the ice and fire mod, because a dragon spawned in our base and destroyed everything. We have Optifine installed on client side. Is there a fix for that?
