### ISSUE TITLE
[BUG] *not loading because "just enough items" keeps preventing mc to open*

### ISSUE THREAD

**Issue by Kitanokoujis** [Minecraft-Eternal/MC-Eternal-Lite-1.12#17]
### Description of the Bug

when I open mc eternal it opens a screen that says that "an error during startup prevented Minecraft from starting the following mods(s) have been identified as potential causes: Just Enough Items"

### Expected Behaviour

to open and send me to the title screen to i would play the modpack

### Modpack Version

1.12.2

### Screenshots

![2022-02-17](https://user-images.githubusercontent.com/99925545/154583312-efbcbb74-ddd9-40b9-abff-d470c03555c9.png)

### Extra Info

when I click the link, it fails to go where the link goes

**Comment by anabsolutesloth** [comment]
Go to the Discord, do `!paste` in our #bot-commands channel, and then provide the paste link in the #client-questions-and-issues channel.
It's a million times faster to handle crash issues like this one on the discord, especially if no log is provided initially.
