### ISSUE TITLE
Bewitchment Focal Chalk not crafting

### ISSUE THREAD

**Issue by Trinagan** [Minecraft-Eternal/MC-Eternal-Lite-1.12#21]
### Description of the Bug

When attempting to create Focal Chalk by tossing Ritual Chalk, Liquid Witchcraft and a Golden Nugget into a cauldron with water which stands over fire/lava it results in the liquid inside the cauldron turning brown and getting nothing back. Tried multiple times, with different timing, and over both fire and lava as mentioned.

### Expected Behaviour

1. Fill up the cauldron with water
2. Toss in Ritual Chalk, Liquid Witchcraft and a Gold Nugget
3. Receive Focal Chalk back and empty the cauldron

### Modpack Version

1.3.8

**Comment by Trinagan** [comment]
This seems to apply to the other 2 chalk crafting as well

**Comment by anabsolutesloth** [comment]
Head to the discord for stuff like this, unless you're confident it's a bug and someone who knows can tell you for sure, don't plop this sort of stuff here, it's not the most active place to get your questions answered.
