### ISSUE TITLE
Passive mobs despawn after leaving a claimed chunk

### ISSUE THREAD

**Issue by ThorneCodes** [Minecraft-Eternal/MC-Eternal-Lite-1.12#3]
All passive mobs despawn from all my claimed chunks when I leave those chunks, even when they're named and the chunk is force loaded. This does not apply to the Doggy Treats dog for some reason

**Comment by anabsolutesloth** [comment]
Are those chunks Chunkloaded? are your Passives indoors? is a large area around them well-lit? if the latter two are not the case, Rifters may be the cause.

**Comment by ThorneCodes** [comment]
I'll try to light up the area and enclose the mobs, I'll keep you posted,
thank you for your time

**Comment by anabsolutesloth** [comment]
Sorry for the late initial response, hadn't checked this page in a while and didn't think there'd be any issues :P

**Comment by ThorneCodes** [comment]
No problem, it was rifters, I went into spectator mode for a few minutes in
another world and saw them take the farm animals from the pen

**Comment by anabsolutesloth** [comment]
Alright, glad that's solved.
