### ISSUE TITLE
[BUG] missing addon

### ISSUE THREAD

**Issue by khamouni** [Minecraft-Eternal/MC-Eternal-Lite-1.12#6]
### Description of the Bug

I've try to install your modpack on my son computer but always get :missing addon 226138

### Expected Behaviour

mod to install (with curseforge)

### Modpack Version

1.12.2

**Comment by anabsolutesloth** [comment]
This is a problem with Curseforge app, i can't fix it, nor can any other packmaker.
For now, just wait it out or try another launcher,
