### ISSUE TITLE
[BUG] *LoliASM causes everyone to crash who comes close*

### ISSUE THREAD

**Issue by koentjeappel** [Minecraft-Eternal/MC-Eternal-Lite-1.12#7]
### Description of the Bug

If you place Meteorite compass on the ground all players close will crash.

Fix: remove mod serverside and client side. 

### Expected Behaviour

To not crash

### Modpack Version

1.3.8 LITE

**Comment by anabsolutesloth** [comment]
Please forward to the mod's author
https://github.com/LoliKingdom/LoliASM/issues
I'm making a quick update that removes it for now.

**Comment by WolfBV** [comment]
Fixed at some point between version 2.5 and version 3.2.1. Also seems to automatically fix BakedQuad issues instead of spamming the console.
